# This GitHub Actions workflow builds a Docker image and pushes it to Docker Hub.
# It triggers on pushes to the 'main' branch (tagging the image as 'latest')
# and on pushes of git tags (e.g., v1.0.0).

name: CI - Push Docker to Hub

on:
  push:
    branches:
      - 'test'
    tags:
      - 'v*.*.*' # This will trigger the action for tags like v1.0.0, v1.2.3, etc.

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # This step logs into Docker Hub using secrets stored in your repository.
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # This action automatically generates tags for your Docker image.
      # - Pushing to 'main' will create the 'latest' tag.
      # - Pushing a git tag like 'v1.2.3' will create the 'v1.2.3' Docker tag.
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # This is the full name of the image on Docker Hub.
          # Make sure it matches your Docker Hub username and desired repository name.
          images: rcvaughn2/pluto-for-channels

      # This is the final step that builds the Docker image from your Dockerfile
      # and pushes it to Docker Hub with the tags generated in the previous step.
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
